<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("cashondeliveryconfig/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("cashondeliveryconfig/new", "Create cash on delivery config")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>SEND Of CITY Of ID</th>
            <th>RECEIVE Of PROVINCE Of ID</th>
            <th>RECEIVE Of CITY Of ID</th>
            <th>RECEIVE Of LOCAL Of ID</th>
            <th>DELIVERY Of TYPE</th>
            <th>PRICE</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>AGENCY Of ID</th>
            <th>IS Of VISIBLE</th>
            <th>RECEIVE Of ZONE Of ID</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $cashondeliveryconfig){ ?>
        <tr>
            <td><?php echo $cashondeliveryconfig->ID ?></td>
            <td><?php echo $cashondeliveryconfig->SEND_CITY_ID ?></td>
            <td><?php echo $cashondeliveryconfig->RECEIVE_PROVINCE_ID ?></td>
            <td><?php echo $cashondeliveryconfig->RECEIVE_CITY_ID ?></td>
            <td><?php echo $cashondeliveryconfig->RECEIVE_LOCAL_ID ?></td>
            <td><?php echo $cashondeliveryconfig->DELIVERY_TYPE ?></td>
            <td><?php echo $cashondeliveryconfig->PRICE ?></td>
            <td><?php echo $cashondeliveryconfig->CREATE_TIME ?></td>
            <td><?php echo $cashondeliveryconfig->UPDATE_TIME ?></td>
            <td><?php echo $cashondeliveryconfig->AGENCY_ID ?></td>
            <td><?php echo $cashondeliveryconfig->IS_VISIBLE ?></td>
            <td><?php echo $cashondeliveryconfig->RECEIVE_ZONE_ID ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cashondeliveryconfig/edit/".$cashondeliveryconfig->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cashondeliveryconfig/delete/".$cashondeliveryconfig->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="12" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondeliveryconfig/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondeliveryconfig/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondeliveryconfig/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondeliveryconfig/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>