<?php echo \Phalcon\Tag::form("appadvertsetting/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("appadvertsetting", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create app advert setting</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEMURL">ITEMURL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEMURL", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IMAGENAME">IMAGENAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IMAGENAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ONLINEID">ONLINEID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ONLINEID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATETIME">UPDATETIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATETIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CRTIME">CRTIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CRTIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USEDSTATUS">USEDSTATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USEDSTATUS", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
