<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("artistimages/new", "Create Artist images")) ?>
</div>

<div align="center">
    <h1>Search artist images</h1>
    <?php echo \Phalcon\Tag::form(array("artistimages/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ARTIST_ID">ARTIST Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ARTIST_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TOTAL">TOTAL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TOTAL", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IMAGE_LIST">IMAGE Of LIST</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("IMAGE_LIST", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_TIME">UPDATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>