<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("artistimages/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("artistimages/new", "Create artist images")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ARTIST Of ID</th>
            <th>TOTAL</th>
            <th>IMAGE Of LIST</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $artistimages){ ?>
        <tr>
            <td><?php echo $artistimages->ID ?></td>
            <td><?php echo $artistimages->ARTIST_ID ?></td>
            <td><?php echo $artistimages->TOTAL ?></td>
            <td><?php echo $artistimages->IMAGE_LIST ?></td>
            <td><?php echo $artistimages->CREATE_TIME ?></td>
            <td><?php echo $artistimages->UPDATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("artistimages/edit/".$artistimages->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("artistimages/delete/".$artistimages->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="6" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("artistimages/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("artistimages/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("artistimages/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("artistimages/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>