<?php echo \Phalcon\Tag::form("luckdrawstock/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("luckdrawstock", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create luck draw stock</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRICE">PRICE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRICE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="STATUS">STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="START_DRAW_TIME">START Of DRAW Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("START_DRAW_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="END_DRAW_TIME">END Of DRAW Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("END_DRAW_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="NUM">NUM</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("NUM", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
