<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("luckdrawstock/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("luckdrawstock/new", "Create luck draw stock")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>PRICE</th>
            <th>STATUS</th>
            <th>START Of DRAW Of TIME</th>
            <th>END Of DRAW Of TIME</th>
            <th>NUM</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $luckdrawstock){ ?>
        <tr>
            <td><?php echo $luckdrawstock->ID ?></td>
            <td><?php echo $luckdrawstock->PRICE ?></td>
            <td><?php echo $luckdrawstock->STATUS ?></td>
            <td><?php echo $luckdrawstock->START_DRAW_TIME ?></td>
            <td><?php echo $luckdrawstock->END_DRAW_TIME ?></td>
            <td><?php echo $luckdrawstock->NUM ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("luckdrawstock/edit/"., "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("luckdrawstock/delete/"., "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="6" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("luckdrawstock/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("luckdrawstock/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("luckdrawstock/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("luckdrawstock/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>