<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("itemtype/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("itemtype/new", "Create item type")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>PID</th>
            <th>NAME</th>
            <th>SORT</th>
            <th>SN</th>
            <th>IS Of VISIBLE</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>NAME Of EN</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $itemtype){ ?>
        <tr>
            <td><?php echo $itemtype->ID ?></td>
            <td><?php echo $itemtype->PID ?></td>
            <td><?php echo $itemtype->NAME ?></td>
            <td><?php echo $itemtype->SORT ?></td>
            <td><?php echo $itemtype->SN ?></td>
            <td><?php echo $itemtype->IS_VISIBLE ?></td>
            <td><?php echo $itemtype->CREATE_TIME ?></td>
            <td><?php echo $itemtype->UPDATE_TIME ?></td>
            <td><?php echo $itemtype->NAME_EN ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemtype/edit/".$itemtype->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemtype/delete/".$itemtype->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="9" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtype/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtype/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtype/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtype/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>