<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("padvancepayment/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("padvancepayment/new", "Create p advance payment")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>UUID</th>
            <th>MONEY</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $padvancepayment){ ?>
        <tr>
            <td><?php echo $padvancepayment->ID ?></td>
            <td><?php echo $padvancepayment->UUID ?></td>
            <td><?php echo $padvancepayment->MONEY ?></td>
            <td><?php echo $padvancepayment->CREATE_TIME ?></td>
            <td><?php echo $padvancepayment->UPDATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("padvancepayment/edit/".$padvancepayment->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("padvancepayment/delete/".$padvancepayment->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="5" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("padvancepayment/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("padvancepayment/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("padvancepayment/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("padvancepayment/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>