<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("partnervenue/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("partnervenue/new", "Create partner venue")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>VENUE Of ID</th>
            <th>PARTNER Of ID</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $partnervenue){ ?>
        <tr>
            <td><?php echo $partnervenue->ID ?></td>
            <td><?php echo $partnervenue->VENUE_ID ?></td>
            <td><?php echo $partnervenue->PARTNER_ID ?></td>
            <td><?php echo $partnervenue->CREATE_TIME ?></td>
            <td><?php echo $partnervenue->UPDATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("partnervenue/edit/".$partnervenue->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("partnervenue/delete/".$partnervenue->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="5" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("partnervenue/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("partnervenue/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("partnervenue/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("partnervenue/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>