<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("itemblock/new", "Create Item block")) ?>
</div>

<div align="center">
    <h1>Search item block</h1>
    <?php echo \Phalcon\Tag::form(array("itemblock/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_ID">ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_TITLE">ITEM Of TITLE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_TITLE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="OP_NAME">OP Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("OP_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IS_BLOCK">IS Of BLOCK</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IS_BLOCK", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>