<?php echo $this->getContent(); ?>

<?php echo \Phalcon\Tag::form("artistdetailinfo/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("artistdetailinfo", "Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton(array("Save")) ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit artistdetailinfo</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ARTIST_ID">ARTIST Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ARTIST_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ARTIST_DESC">ARTIST Of DESC</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("ARTIST_DESC", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_TIME">UPDATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ARTIST_DETAIL_DESC">ARTIST Of DETAIL Of DESC</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("ARTIST_DETAIL_DESC", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ARTIST_OTHER_PROPERTY">ARTIST Of OTHER Of PROPERTY</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("ARTIST_OTHER_PROPERTY", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
    </table>
    <?php echo \Phalcon\Tag::endForm() ?>
