<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("artistdetailinfo/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("artistdetailinfo/new", "Create artist detail info")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ARTIST Of ID</th>
            <th>ARTIST Of DESC</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>ARTIST Of DETAIL Of DESC</th>
            <th>ARTIST Of OTHER Of PROPERTY</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $artistdetailinfo){ ?>
        <tr>
            <td><?php echo $artistdetailinfo->ID ?></td>
            <td><?php echo $artistdetailinfo->ARTIST_ID ?></td>
            <td><?php echo $artistdetailinfo->ARTIST_DESC ?></td>
            <td><?php echo $artistdetailinfo->CREATE_TIME ?></td>
            <td><?php echo $artistdetailinfo->UPDATE_TIME ?></td>
            <td><?php echo $artistdetailinfo->ARTIST_DETAIL_DESC ?></td>
            <td><?php echo $artistdetailinfo->ARTIST_OTHER_PROPERTY ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("artistdetailinfo/edit/".$artistdetailinfo->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("artistdetailinfo/delete/".$artistdetailinfo->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="7" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("artistdetailinfo/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("artistdetailinfo/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("artistdetailinfo/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("artistdetailinfo/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>