<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("priceinfo/new", "Create Price info")) ?>
</div>

<div align="center">
    <h1>Search price info</h1>
    <?php echo \Phalcon\Tag::form(array("priceinfo/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SENCE_ID">SENCE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SENCE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_ID">ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ONLINE_ID">ONLINE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ONLINE_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="NAME">NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SORT">SORT</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SORT", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRICE">PRICE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRICE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COST_PRICE">COST Of PRICE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COST_PRICE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SELL_PRICE">SELL Of PRICE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SELL_PRICE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DISCOUNT">DISCOUNT</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DISCOUNT", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SELL_NUM">SELL Of NUM</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SELL_NUM", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRICE_TYPE">PRICE Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRICE_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRICE_LEVEL">PRICE Of LEVEL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRICE_LEVEL", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRICE_STATUS">PRICE Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRICE_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TOTAL">TOTAL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TOTAL", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REMARK">REMARK</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REMARK", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_TIME">UPDATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOW_START_TIME">SHOW Of START Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOW_START_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="XSZC_ID">XSZC Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("XSZC_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PJDJ">PJDJ</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PJDJ", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="OPT">OPT</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("OPT", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="GROUP_NAME">GROUP Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("GROUP_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="THIRDPRICEID">THIRDPRICEID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("THIRDPRICEID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="THIRDITEMID">THIRDITEMID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("THIRDITEMID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="THIRDSCENEID">THIRDSCENEID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("THIRDSCENEID", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>