<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("priceinfo/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("priceinfo/new", "Create price info")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>SENCE Of ID</th>
            <th>ITEM Of ID</th>
            <th>ONLINE Of ID</th>
            <th>NAME</th>
            <th>SORT</th>
            <th>PRICE</th>
            <th>COST Of PRICE</th>
            <th>SELL Of PRICE</th>
            <th>DISCOUNT</th>
            <th>SELL Of NUM</th>
            <th>PRICE Of TYPE</th>
            <th>PRICE Of LEVEL</th>
            <th>PRICE Of STATUS</th>
            <th>TOTAL</th>
            <th>REMARK</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>SHOW Of START Of TIME</th>
            <th>XSZC Of ID</th>
            <th>PJDJ</th>
            <th>OPT</th>
            <th>GROUP Of NAME</th>
            <th>THIRDPRICEID</th>
            <th>THIRDITEMID</th>
            <th>THIRDSCENEID</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $priceinfo){ ?>
        <tr>
            <td><?php echo $priceinfo->ID ?></td>
            <td><?php echo $priceinfo->SENCE_ID ?></td>
            <td><?php echo $priceinfo->ITEM_ID ?></td>
            <td><?php echo $priceinfo->ONLINE_ID ?></td>
            <td><?php echo $priceinfo->NAME ?></td>
            <td><?php echo $priceinfo->SORT ?></td>
            <td><?php echo $priceinfo->PRICE ?></td>
            <td><?php echo $priceinfo->COST_PRICE ?></td>
            <td><?php echo $priceinfo->SELL_PRICE ?></td>
            <td><?php echo $priceinfo->DISCOUNT ?></td>
            <td><?php echo $priceinfo->SELL_NUM ?></td>
            <td><?php echo $priceinfo->PRICE_TYPE ?></td>
            <td><?php echo $priceinfo->PRICE_LEVEL ?></td>
            <td><?php echo $priceinfo->PRICE_STATUS ?></td>
            <td><?php echo $priceinfo->TOTAL ?></td>
            <td><?php echo $priceinfo->REMARK ?></td>
            <td><?php echo $priceinfo->CREATE_TIME ?></td>
            <td><?php echo $priceinfo->UPDATE_TIME ?></td>
            <td><?php echo $priceinfo->SHOW_START_TIME ?></td>
            <td><?php echo $priceinfo->XSZC_ID ?></td>
            <td><?php echo $priceinfo->PJDJ ?></td>
            <td><?php echo $priceinfo->OPT ?></td>
            <td><?php echo $priceinfo->GROUP_NAME ?></td>
            <td><?php echo $priceinfo->THIRDPRICEID ?></td>
            <td><?php echo $priceinfo->THIRDITEMID ?></td>
            <td><?php echo $priceinfo->THIRDSCENEID ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("priceinfo/edit/".$priceinfo->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("priceinfo/delete/".$priceinfo->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="26" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("priceinfo/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("priceinfo/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("priceinfo/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("priceinfo/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>