<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("foreignorderrelation/new", "Create Foreign order relation")) ?>
</div>

<div align="center">
    <h1>Search foreign order relation</h1>
    <?php echo \Phalcon\Tag::form(array("foreignorderrelation/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PACKAGE_ID">PACKAGE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PACKAGE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="FOREIGN_ORDER_ID">FOREIGN Of ORDER Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("FOREIGN_ORDER_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="FOREIGN_ORDER_CONTEXT">FOREIGN Of ORDER Of CONTEXT</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("FOREIGN_ORDER_CONTEXT", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>