<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("pworderclearqueue/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("pworderclearqueue/new", "Create pw order clear queue")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>PIAOWU Of ORDER Of ID</th>
            <th>OPERATE Of NUMBER</th>
            <th>CREATE Of TIME</th>
            <th>QIANG</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $pworderclearqueue){ ?>
        <tr>
            <td><?php echo $pworderclearqueue->ID ?></td>
            <td><?php echo $pworderclearqueue->PIAOWU_ORDER_ID ?></td>
            <td><?php echo $pworderclearqueue->OPERATE_NUMBER ?></td>
            <td><?php echo $pworderclearqueue->CREATE_TIME ?></td>
            <td><?php echo $pworderclearqueue->QIANG ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("pworderclearqueue/edit/".$pworderclearqueue->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("pworderclearqueue/delete/".$pworderclearqueue->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="5" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("pworderclearqueue/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("pworderclearqueue/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("pworderclearqueue/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("pworderclearqueue/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>