<?php echo $this->getContent(); ?>

<?php echo \Phalcon\Tag::form("bbbhelp/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("bbbhelp", "Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton(array("Save")) ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit bbbhelp</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PHONE">PHONE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PHONE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SCORE">SCORE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SCORE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATETIME">UPDATETIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATETIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CRTIME">CRTIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CRTIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COOKIESID">COOKIESID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COOKIESID", "size" => 30)) ?>
            </td>
        </tr>
    </table>
    <?php echo \Phalcon\Tag::endForm() ?>
