<?php echo $this->getContent(); ?>

<?php echo \Phalcon\Tag::form("ppaymenttypelog/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("ppaymenttypelog", "Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton(array("Save")) ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit ppaymenttypelog</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USER_ID">USER Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USER_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COMM">COMM</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COMM", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TYPE_ID">TYPE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TYPE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
    <?php echo \Phalcon\Tag::endForm() ?>
