<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("porderfinishlog/new", "Create P order finish log")) ?>
</div>

<div align="center">
    <h1>Search p order finish log</h1>
    <?php echo \Phalcon\Tag::form(array("porderfinishlog/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TYPE">TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CHARGE_NO">CHARGE Of NO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CHARGE_NO", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ORDERNO">ORDERNO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ORDERNO", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="OPERATE_NUMBER">OPERATE Of NUMBER</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("OPERATE_NUMBER", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="LOG_OPERATE">LOG Of OPERATE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("LOG_OPERATE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="LOG_CREATE_TIME">LOG Of CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("LOG_CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PACKAGE_ID">PACKAGE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PACKAGE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PAYMENT_TIME">PAYMENT Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PAYMENT_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="MONEY_BASE_FEN">MONEY Of BASE Of FEN</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("MONEY_BASE_FEN", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REFUND_MONEY_BASE_FEN">REFUND Of MONEY Of BASE Of FEN</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REFUND_MONEY_BASE_FEN", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_UUID">PERSON Of UUID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_UUID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_NAME">PERSON Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_AGENCY_ID">PERSON Of AGENCY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_AGENCY_ID", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>