<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("porderfinishlog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("porderfinishlog/new", "Create p order finish log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>TYPE</th>
            <th>CHARGE Of NO</th>
            <th>ORDERNO</th>
            <th>OPERATE Of NUMBER</th>
            <th>CREATE Of TIME</th>
            <th>LOG Of OPERATE</th>
            <th>LOG Of CREATE Of TIME</th>
            <th>PACKAGE Of ID</th>
            <th>PAYMENT Of TIME</th>
            <th>MONEY Of BASE Of FEN</th>
            <th>REFUND Of MONEY Of BASE Of FEN</th>
            <th>PERSON Of UUID</th>
            <th>PERSON Of NAME</th>
            <th>PERSON Of AGENCY Of ID</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $porderfinishlog){ ?>
        <tr>
            <td><?php echo $porderfinishlog->ID ?></td>
            <td><?php echo $porderfinishlog->TYPE ?></td>
            <td><?php echo $porderfinishlog->CHARGE_NO ?></td>
            <td><?php echo $porderfinishlog->ORDERNO ?></td>
            <td><?php echo $porderfinishlog->OPERATE_NUMBER ?></td>
            <td><?php echo $porderfinishlog->CREATE_TIME ?></td>
            <td><?php echo $porderfinishlog->LOG_OPERATE ?></td>
            <td><?php echo $porderfinishlog->LOG_CREATE_TIME ?></td>
            <td><?php echo $porderfinishlog->PACKAGE_ID ?></td>
            <td><?php echo $porderfinishlog->PAYMENT_TIME ?></td>
            <td><?php echo $porderfinishlog->MONEY_BASE_FEN ?></td>
            <td><?php echo $porderfinishlog->REFUND_MONEY_BASE_FEN ?></td>
            <td><?php echo $porderfinishlog->PERSON_UUID ?></td>
            <td><?php echo $porderfinishlog->PERSON_NAME ?></td>
            <td><?php echo $porderfinishlog->PERSON_AGENCY_ID ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("porderfinishlog/edit/".$porderfinishlog->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("porderfinishlog/delete/".$porderfinishlog->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="15" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("porderfinishlog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("porderfinishlog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("porderfinishlog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("porderfinishlog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>