<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("pitempayment/new", "Create P item payment")) ?>
</div>

<div align="center">
    <h1>Search p item payment</h1>
    <?php echo \Phalcon\Tag::form(array("pitempayment/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TYPE_ID">TYPE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TYPE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_ID">ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PARTY_ID">PARTY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PARTY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AGENCY_ID">AGENCY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AGENCY_ID", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>