<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("hjmobile/new", "Create Hj mobile")) ?>
</div>

<div align="center">
    <h1>Search hj mobile</h1>
    <?php echo \Phalcon\Tag::form(array("hjmobile/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="MOBILE">MOBILE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("MOBILE", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>