<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("hjmobile/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("hjmobile/new", "Create hj mobile")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>MOBILE</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $hjmobile){ ?>
        <tr>
            <td><?php echo $hjmobile->MOBILE ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("hjmobile/edit/"., "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("hjmobile/delete/"., "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="1" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("hjmobile/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("hjmobile/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("hjmobile/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("hjmobile/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>