<?php echo \Phalcon\Tag::form("financestatisticitem/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("financestatisticitem", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create finance statistic item</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ITEM_NAME">ITEM Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COMPANY">COMPANY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COMPANY", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PLACE">PLACE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PLACE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOW_START_TIME">SHOW Of START Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOW_START_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOW_END_TIME">SHOW Of END Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOW_END_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TICKET_SYS_DIC_ID">TICKET Of SYS Of DIC Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TICKET_SYS_DIC_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CLEARING_PARTY">CLEARING Of PARTY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CLEARING_PARTY", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IS_CONTACT">IS Of CONTACT</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IS_CONTACT", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_TIME">UPDATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_USER_ID">UPDATE Of USER Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_USER_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
