<?php echo \Phalcon\Tag::form("ppaymentrefund/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("ppaymentrefund", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create p payment refund</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="BATCH_NO">BATCH Of NO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("BATCH_NO", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PACKAGE_ID">PACKAGE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PACKAGE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PARTNER_ORDER_NO">PARTNER Of ORDER Of NO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PARTNER_ORDER_NO", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="MONEY_BASE_FEN">MONEY Of BASE Of FEN</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("MONEY_BASE_FEN", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REFUND_MONEY_BASE_FEN">REFUND Of MONEY Of BASE Of FEN</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REFUND_MONEY_BASE_FEN", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REASON">REASON</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REASON", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="NOTIFY_STATUS">NOTIFY Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("NOTIFY_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REFUND_TIME">REFUND Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REFUND_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TYPE_ID">TYPE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TYPE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PAYMENT_TIME">PAYMENT Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PAYMENT_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CHARGE_NO">CHARGE Of NO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CHARGE_NO", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_UUID">PERSON Of UUID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_UUID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_NAME">PERSON Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_AGENCY_ID">PERSON Of AGENCY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_AGENCY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
