<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("carrearageuserlog/new", "Create C arrearage user log")) ?>
</div>

<div align="center">
    <h1>Search c arrearage user log</h1>
    <?php echo \Phalcon\Tag::form(array("carrearageuserlog/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USER_ID">USER Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USER_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COMM">COMM</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COMM", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>