<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("carrearageuserlog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("carrearageuserlog/new", "Create c arrearage user log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>USER Of ID</th>
            <th>COMM</th>
            <th>CREATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $carrearageuserlog){ ?>
        <tr>
            <td><?php echo $carrearageuserlog->ID ?></td>
            <td><?php echo $carrearageuserlog->USER_ID ?></td>
            <td><?php echo $carrearageuserlog->COMM ?></td>
            <td><?php echo $carrearageuserlog->CREATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("carrearageuserlog/edit/".$carrearageuserlog->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("carrearageuserlog/delete/".$carrearageuserlog->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="4" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuserlog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuserlog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuserlog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuserlog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>