<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("oorderoperator/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("oorderoperator/new", "Create o order operator")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ORDER Of ID</th>
            <th>DEAL Of ID</th>
            <th>DEAL Of AGENCY Of ID</th>
            <th>PRINT Of USER Of ID</th>
            <th>PRINT Of AGENCY Of ID</th>
            <th>CREATE Of USER Of ID</th>
            <th>CREATE Of AGENCY Of ID</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $oorderoperator){ ?>
        <tr>
            <td><?php echo $oorderoperator->ID ?></td>
            <td><?php echo $oorderoperator->ORDER_ID ?></td>
            <td><?php echo $oorderoperator->DEAL_ID ?></td>
            <td><?php echo $oorderoperator->DEAL_AGENCY_ID ?></td>
            <td><?php echo $oorderoperator->PRINT_USER_ID ?></td>
            <td><?php echo $oorderoperator->PRINT_AGENCY_ID ?></td>
            <td><?php echo $oorderoperator->CREATE_USER_ID ?></td>
            <td><?php echo $oorderoperator->CREATE_AGENCY_ID ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("oorderoperator/edit/".$oorderoperator->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("oorderoperator/delete/".$oorderoperator->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="8" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderoperator/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderoperator/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderoperator/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderoperator/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>