<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("cashondelivery/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("cashondelivery/new", "Create cash on delivery")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>AGENCY Of ID</th>
            <th>SEND Of CITY Of ID</th>
            <th>DELIVERY Of TYPE</th>
            <th>DELIVERY Of SCOPE</th>
            <th>ADD Of CONDITION</th>
            <th>REMARK</th>
            <th>IS Of VISIBEL</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $cashondelivery){ ?>
        <tr>
            <td><?php echo $cashondelivery->ID ?></td>
            <td><?php echo $cashondelivery->AGENCY_ID ?></td>
            <td><?php echo $cashondelivery->SEND_CITY_ID ?></td>
            <td><?php echo $cashondelivery->DELIVERY_TYPE ?></td>
            <td><?php echo $cashondelivery->DELIVERY_SCOPE ?></td>
            <td><?php echo $cashondelivery->ADD_CONDITION ?></td>
            <td><?php echo $cashondelivery->REMARK ?></td>
            <td><?php echo $cashondelivery->IS_VISIBEL ?></td>
            <td><?php echo $cashondelivery->CREATE_TIME ?></td>
            <td><?php echo $cashondelivery->UPDATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cashondelivery/edit/".$cashondelivery->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cashondelivery/delete/".$cashondelivery->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="10" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondelivery/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondelivery/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondelivery/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cashondelivery/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>