<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("cardinfo/new", "Create Card info")) ?>
</div>

<div align="center">
    <h1>Search card info</h1>
    <?php echo \Phalcon\Tag::form(array("cardinfo/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textField(array("ID")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="BATCH_ID">BATCH Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("BATCH_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CARD_NO">CARD Of NO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CARD_NO", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CARD_PWD">CARD Of PWD</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CARD_PWD", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AUDIT_STATUS">AUDIT Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AUDIT_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>