<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("panicbuyticket/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("panicbuyticket/new", "Create panic buy ticket")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>SCENE Of ID</th>
            <th>ITEM Of ID</th>
            <th>STATUS</th>
            <th>IS Of VISIBLE</th>
            <th>CREATE Of TIME</th>
            <th>CREATE Of UUID</th>
            <th>UPDATE Of TIME</th>
            <th>UPDATE Of UUID</th>
            <th>SELL Of NUM</th>
            <th>SYNC Of SELL Of NUM</th>
            <th>START Of TIME</th>
            <th>END Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $panicbuyticket){ ?>
        <tr>
            <td><?php echo $panicbuyticket->ID ?></td>
            <td><?php echo $panicbuyticket->SCENE_ID ?></td>
            <td><?php echo $panicbuyticket->ITEM_ID ?></td>
            <td><?php echo $panicbuyticket->STATUS ?></td>
            <td><?php echo $panicbuyticket->IS_VISIBLE ?></td>
            <td><?php echo $panicbuyticket->CREATE_TIME ?></td>
            <td><?php echo $panicbuyticket->CREATE_UUID ?></td>
            <td><?php echo $panicbuyticket->UPDATE_TIME ?></td>
            <td><?php echo $panicbuyticket->UPDATE_UUID ?></td>
            <td><?php echo $panicbuyticket->SELL_NUM ?></td>
            <td><?php echo $panicbuyticket->SYNC_SELL_NUM ?></td>
            <td><?php echo $panicbuyticket->START_TIME ?></td>
            <td><?php echo $panicbuyticket->END_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("panicbuyticket/edit/".$panicbuyticket->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("panicbuyticket/delete/".$panicbuyticket->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="13" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("panicbuyticket/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("panicbuyticket/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("panicbuyticket/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("panicbuyticket/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>