<?php echo $this->getContent(); ?>

<?php echo \Phalcon\Tag::form("itempaymentconfig/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("itempaymentconfig", "Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton(array("Save")) ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit itempaymentconfig</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ONLINE_ID">ONLINE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ONLINE_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_TIME">UPDATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PAYMENT_CONFIG">PAYMENT Of CONFIG</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("PAYMENT_CONFIG", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IS_AGENCY_DEFAULT">IS Of AGENCY Of DEFAULT</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IS_AGENCY_DEFAULT", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
    <?php echo \Phalcon\Tag::endForm() ?>
