<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("itempaymentconfig/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("itempaymentconfig/new", "Create item payment config")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ONLINE Of ID</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>PAYMENT Of CONFIG</th>
            <th>IS Of AGENCY Of DEFAULT</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $itempaymentconfig){ ?>
        <tr>
            <td><?php echo $itempaymentconfig->ID ?></td>
            <td><?php echo $itempaymentconfig->ONLINE_ID ?></td>
            <td><?php echo $itempaymentconfig->CREATE_TIME ?></td>
            <td><?php echo $itempaymentconfig->UPDATE_TIME ?></td>
            <td><?php echo $itempaymentconfig->PAYMENT_CONFIG ?></td>
            <td><?php echo $itempaymentconfig->IS_AGENCY_DEFAULT ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itempaymentconfig/edit/".$itempaymentconfig->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itempaymentconfig/delete/".$itempaymentconfig->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="6" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("itempaymentconfig/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itempaymentconfig/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itempaymentconfig/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itempaymentconfig/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>