<?php echo \Phalcon\Tag::form("iteminfolog/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("iteminfolog", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create item info log</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_ID">ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ONLINE_ID">ONLINE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ONLINE_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CONTENT">CONTENT</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("CONTENT", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_UUID">PERSON Of UUID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_UUID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PERSON_NAME">PERSON Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PERSON_NAME", "size" => 30)) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
