<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("iteminfolog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("iteminfolog/new", "Create item info log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ITEM Of ID</th>
            <th>ONLINE Of ID</th>
            <th>CONTENT</th>
            <th>CREATE Of TIME</th>
            <th>PERSON Of UUID</th>
            <th>PERSON Of NAME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $iteminfolog){ ?>
        <tr>
            <td><?php echo $iteminfolog->ID ?></td>
            <td><?php echo $iteminfolog->ITEM_ID ?></td>
            <td><?php echo $iteminfolog->ONLINE_ID ?></td>
            <td><?php echo $iteminfolog->CONTENT ?></td>
            <td><?php echo $iteminfolog->CREATE_TIME ?></td>
            <td><?php echo $iteminfolog->PERSON_UUID ?></td>
            <td><?php echo $iteminfolog->PERSON_NAME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("iteminfolog/edit/".$iteminfolog->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("iteminfolog/delete/".$iteminfolog->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="7" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfolog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfolog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfolog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfolog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>