<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("cothersdbuserlog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("cothersdbuserlog/new", "Create c others dbuser log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>USER Of ID</th>
            <th>COMM</th>
            <th>CREATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $cothersdbuserlog){ ?>
        <tr>
            <td><?php echo $cothersdbuserlog->ID ?></td>
            <td><?php echo $cothersdbuserlog->USER_ID ?></td>
            <td><?php echo $cothersdbuserlog->COMM ?></td>
            <td><?php echo $cothersdbuserlog->CREATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cothersdbuserlog/edit/".$cothersdbuserlog->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cothersdbuserlog/delete/".$cothersdbuserlog->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="4" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("cothersdbuserlog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cothersdbuserlog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cothersdbuserlog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cothersdbuserlog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>