<?php echo $this->getContent(); ?>

<?php echo \Phalcon\Tag::form("iteminfo/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("iteminfo", "Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton(array("Save")) ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit iteminfo</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_ID">ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_TITLE">ITEM Of TITLE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_TITLE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_SHORT_TITLE">ITEM Of SHORT Of TITLE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_SHORT_TITLE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CITY_ID">CITY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CITY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="VENUE_ID">VENUE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("VENUE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AGENCY_ID">AGENCY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AGENCY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TICKET_SYS_DIC_ID">TICKET Of SYS Of DIC Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TICKET_SYS_DIC_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PROXY_TYPE">PROXY Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PROXY_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOW_TYPE">SHOW Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOW_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOW_TIME">SHOW Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOW_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRICE_INFO">PRICE Of INFO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRICE_INFO", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ARTIST_ID">ARTIST Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ARTIST_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_TYPE_ID">ITEM Of TYPE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_TYPE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_TYPE_PID">ITEM Of TYPE Of PID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_TYPE_PID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_IMAGE_URL">ITEM Of IMAGE Of URL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_IMAGE_URL", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SEATS_IMAGE_URL">SEATS Of IMAGE Of URL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SEATS_IMAGE_URL", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AUDIT_STATUS">AUDIT Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AUDIT_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IS_VISIBLE">IS Of VISIBLE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IS_VISIBLE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ASSOCIATE_ITEM_ID">ASSOCIATE Of ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ASSOCIATE_ITEM_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATE_TIME">UPDATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_TAG">ITEM Of TAG</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("ITEM_TAG", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DOUBAN_REVIEW_ID">DOUBAN Of REVIEW Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DOUBAN_REVIEW_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOW_END_TIME">SHOW Of END Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOW_END_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PROXY_TAX">PROXY Of TAX</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PROXY_TAX", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IS_ETICKET">IS Of ETICKET</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IS_ETICKET", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="LIMIT_CHOICE">LIMIT Of CHOICE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("LIMIT_CHOICE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="EXCHANGE_TYPE">EXCHANGE Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("EXCHANGE_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="THIRDITEMID">THIRDITEMID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("THIRDITEMID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IS_REALNAME">IS Of REALNAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IS_REALNAME", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
    <?php echo \Phalcon\Tag::endForm() ?>
