<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("iteminfo/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("iteminfo/new", "Create item info")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ITEM Of ID</th>
            <th>ITEM Of TITLE</th>
            <th>ITEM Of SHORT Of TITLE</th>
            <th>CITY Of ID</th>
            <th>VENUE Of ID</th>
            <th>AGENCY Of ID</th>
            <th>TICKET Of SYS Of DIC Of ID</th>
            <th>PROXY Of TYPE</th>
            <th>SHOW Of TYPE</th>
            <th>SHOW Of TIME</th>
            <th>PRICE Of INFO</th>
            <th>ARTIST Of ID</th>
            <th>ITEM Of TYPE Of ID</th>
            <th>ITEM Of TYPE Of PID</th>
            <th>ITEM Of IMAGE Of URL</th>
            <th>SEATS Of IMAGE Of URL</th>
            <th>AUDIT Of STATUS</th>
            <th>IS Of VISIBLE</th>
            <th>ASSOCIATE Of ITEM Of ID</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>ITEM Of TAG</th>
            <th>DOUBAN Of REVIEW Of ID</th>
            <th>SHOW Of END Of TIME</th>
            <th>PROXY Of TAX</th>
            <th>IS Of ETICKET</th>
            <th>LIMIT Of CHOICE</th>
            <th>EXCHANGE Of TYPE</th>
            <th>THIRDITEMID</th>
            <th>IS Of REALNAME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $iteminfo){ ?>
        <tr>
            <td><?php echo $iteminfo->ID ?></td>
            <td><?php echo $iteminfo->ITEM_ID ?></td>
            <td><?php echo $iteminfo->ITEM_TITLE ?></td>
            <td><?php echo $iteminfo->ITEM_SHORT_TITLE ?></td>
            <td><?php echo $iteminfo->CITY_ID ?></td>
            <td><?php echo $iteminfo->VENUE_ID ?></td>
            <td><?php echo $iteminfo->AGENCY_ID ?></td>
            <td><?php echo $iteminfo->TICKET_SYS_DIC_ID ?></td>
            <td><?php echo $iteminfo->PROXY_TYPE ?></td>
            <td><?php echo $iteminfo->SHOW_TYPE ?></td>
            <td><?php echo $iteminfo->SHOW_TIME ?></td>
            <td><?php echo $iteminfo->PRICE_INFO ?></td>
            <td><?php echo $iteminfo->ARTIST_ID ?></td>
            <td><?php echo $iteminfo->ITEM_TYPE_ID ?></td>
            <td><?php echo $iteminfo->ITEM_TYPE_PID ?></td>
            <td><?php echo $iteminfo->ITEM_IMAGE_URL ?></td>
            <td><?php echo $iteminfo->SEATS_IMAGE_URL ?></td>
            <td><?php echo $iteminfo->AUDIT_STATUS ?></td>
            <td><?php echo $iteminfo->IS_VISIBLE ?></td>
            <td><?php echo $iteminfo->ASSOCIATE_ITEM_ID ?></td>
            <td><?php echo $iteminfo->CREATE_TIME ?></td>
            <td><?php echo $iteminfo->UPDATE_TIME ?></td>
            <td><?php echo $iteminfo->ITEM_TAG ?></td>
            <td><?php echo $iteminfo->DOUBAN_REVIEW_ID ?></td>
            <td><?php echo $iteminfo->SHOW_END_TIME ?></td>
            <td><?php echo $iteminfo->PROXY_TAX ?></td>
            <td><?php echo $iteminfo->IS_ETICKET ?></td>
            <td><?php echo $iteminfo->LIMIT_CHOICE ?></td>
            <td><?php echo $iteminfo->EXCHANGE_TYPE ?></td>
            <td><?php echo $iteminfo->THIRDITEMID ?></td>
            <td><?php echo $iteminfo->IS_REALNAME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("iteminfo/edit/".$iteminfo->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("iteminfo/delete/".$iteminfo->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="31" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfo/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfo/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfo/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("iteminfo/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>