<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("cardbatch/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("cardbatch/new", "Create card batch")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>BATCH Of ID</th>
            <th>CARD Of NUM</th>
            <th>CREATE Of UUID</th>
            <th>CREATE Of NAME</th>
            <th>CREATE Of TIME</th>
            <th>FILE Of URL</th>
            <th>AUDIT Of STATUS</th>
            <th>AUDIT Of UUID</th>
            <th>AUDIT Of NAME</th>
            <th>AUDIT Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $cardbatch){ ?>
        <tr>
            <td><?php echo $cardbatch->ID ?></td>
            <td><?php echo $cardbatch->BATCH_ID ?></td>
            <td><?php echo $cardbatch->CARD_NUM ?></td>
            <td><?php echo $cardbatch->CREATE_UUID ?></td>
            <td><?php echo $cardbatch->CREATE_NAME ?></td>
            <td><?php echo $cardbatch->CREATE_TIME ?></td>
            <td><?php echo $cardbatch->FILE_URL ?></td>
            <td><?php echo $cardbatch->AUDIT_STATUS ?></td>
            <td><?php echo $cardbatch->AUDIT_UUID ?></td>
            <td><?php echo $cardbatch->AUDIT_NAME ?></td>
            <td><?php echo $cardbatch->AUDIT_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cardbatch/edit/".$cardbatch->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("cardbatch/delete/".$cardbatch->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="11" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("cardbatch/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cardbatch/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cardbatch/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("cardbatch/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>