<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("oordersettle/new", "Create O order settle")) ?>
</div>

<div align="center">
    <h1>Search o order settle</h1>
    <?php echo \Phalcon\Tag::form(array("oordersettle/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ORDER_ID">ORDER Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ORDER_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SETTLE_STATUS">SETTLE Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SETTLE_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRE_SETTLE_TIME">PRE Of SETTLE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRE_SETTLE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SETTLE_DONE_TIME">SETTLE Of DONE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SETTLE_DONE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PRE_SETTLE_OPERATOR">PRE Of SETTLE Of OPERATOR</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PRE_SETTLE_OPERATOR", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SETTLE_DONE_OPERATOR">SETTLE Of DONE Of OPERATOR</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SETTLE_DONE_OPERATOR", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>