<?php echo \Phalcon\Tag::form("opackage/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("opackage", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create o package</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UUID">UUID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UUID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="INVOICE">INVOICE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("INVOICE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="INVOICE_TITLE">INVOICE Of TITLE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("INVOICE_TITLE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="INVOICE_CONTENT">INVOICE Of CONTENT</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("INVOICE_CONTENT", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_CITY_ID">DELIVERY Of CITY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_CITY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_TYPE">DELIVERY Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_TIME">DELIVERY Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USERNAME">REACH Of USERNAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USERNAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_EMAIL">REACH Of USER Of EMAIL</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_EMAIL", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_ADDRESS">REACH Of USER Of ADDRESS</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("REACH_USER_ADDRESS", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_PHONE">REACH Of USER Of PHONE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_PHONE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_PROVINCE">REACH Of USER Of PROVINCE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_PROVINCE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_CITY">REACH Of USER Of CITY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_CITY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_LOCALITY">REACH Of USER Of LOCALITY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_LOCALITY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_ZONE">REACH Of USER Of ZONE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_ZONE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REACH_USER_ZIPCODE">REACH Of USER Of ZIPCODE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REACH_USER_ZIPCODE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_PERSON_ID">DELIVERY Of PERSON Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_PERSON_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_PERSON_NAME">DELIVERY Of PERSON Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_PERSON_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_STATUS">DELIVERY Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_NO">DELIVERY Of NO</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_NO", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REMARKS">REMARKS</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("REMARKS", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="MONEY">MONEY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("MONEY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COURIER">COURIER</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COURIER", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHOULD_PAY">SHOULD Of PAY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHOULD_PAY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PACKAGE_ID">PACKAGE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PACKAGE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PAYMENT_STATUS">PAYMENT Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PAYMENT_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AGENCYID">AGENCYID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AGENCYID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AGENCY_ID">AGENCY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AGENCY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DELIVERY_COMPANY">DELIVERY Of COMPANY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DELIVERY_COMPANY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ORDER_TOTAL_MONEY">ORDER Of TOTAL Of MONEY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ORDER_TOTAL_MONEY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ORDER_DISCOUNT_TOTAL_MONEY">ORDER Of DISCOUNT Of TOTAL Of MONEY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ORDER_DISCOUNT_TOTAL_MONEY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="VIRTUAL_MONEY">VIRTUAL Of MONEY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("VIRTUAL_MONEY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="VIRTUAL_MONEY_TYPE">VIRTUAL Of MONEY Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("VIRTUAL_MONEY_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COD">COD</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COD", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PAYMENT_CLASS">PAYMENT Of CLASS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PAYMENT_CLASS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="REAL_PAY">REAL Of PAY</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("REAL_PAY", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USERNAME">USERNAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USERNAME", "size" => 30)) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
