<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("opackage/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("opackage/new", "Create o package")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>UUID</th>
            <th>INVOICE</th>
            <th>INVOICE Of TITLE</th>
            <th>INVOICE Of CONTENT</th>
            <th>DELIVERY Of CITY Of ID</th>
            <th>DELIVERY Of TYPE</th>
            <th>DELIVERY Of TIME</th>
            <th>REACH Of USERNAME</th>
            <th>REACH Of USER Of EMAIL</th>
            <th>REACH Of USER Of ADDRESS</th>
            <th>REACH Of USER Of PHONE</th>
            <th>REACH Of USER Of PROVINCE</th>
            <th>REACH Of USER Of CITY</th>
            <th>REACH Of USER Of LOCALITY</th>
            <th>REACH Of USER Of ZONE</th>
            <th>REACH Of USER Of ZIPCODE</th>
            <th>DELIVERY Of PERSON Of ID</th>
            <th>DELIVERY Of PERSON Of NAME</th>
            <th>DELIVERY Of STATUS</th>
            <th>DELIVERY Of NO</th>
            <th>REMARKS</th>
            <th>MONEY</th>
            <th>COURIER</th>
            <th>SHOULD Of PAY</th>
            <th>CREATE Of TIME</th>
            <th>PACKAGE Of ID</th>
            <th>PAYMENT Of STATUS</th>
            <th>AGENCYID</th>
            <th>AGENCY Of ID</th>
            <th>DELIVERY Of COMPANY</th>
            <th>ORDER Of TOTAL Of MONEY</th>
            <th>ORDER Of DISCOUNT Of TOTAL Of MONEY</th>
            <th>VIRTUAL Of MONEY</th>
            <th>VIRTUAL Of MONEY Of TYPE</th>
            <th>COD</th>
            <th>PAYMENT Of CLASS</th>
            <th>REAL Of PAY</th>
            <th>USERNAME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $opackage){ ?>
        <tr>
            <td><?php echo $opackage->ID ?></td>
            <td><?php echo $opackage->UUID ?></td>
            <td><?php echo $opackage->INVOICE ?></td>
            <td><?php echo $opackage->INVOICE_TITLE ?></td>
            <td><?php echo $opackage->INVOICE_CONTENT ?></td>
            <td><?php echo $opackage->DELIVERY_CITY_ID ?></td>
            <td><?php echo $opackage->DELIVERY_TYPE ?></td>
            <td><?php echo $opackage->DELIVERY_TIME ?></td>
            <td><?php echo $opackage->REACH_USERNAME ?></td>
            <td><?php echo $opackage->REACH_USER_EMAIL ?></td>
            <td><?php echo $opackage->REACH_USER_ADDRESS ?></td>
            <td><?php echo $opackage->REACH_USER_PHONE ?></td>
            <td><?php echo $opackage->REACH_USER_PROVINCE ?></td>
            <td><?php echo $opackage->REACH_USER_CITY ?></td>
            <td><?php echo $opackage->REACH_USER_LOCALITY ?></td>
            <td><?php echo $opackage->REACH_USER_ZONE ?></td>
            <td><?php echo $opackage->REACH_USER_ZIPCODE ?></td>
            <td><?php echo $opackage->DELIVERY_PERSON_ID ?></td>
            <td><?php echo $opackage->DELIVERY_PERSON_NAME ?></td>
            <td><?php echo $opackage->DELIVERY_STATUS ?></td>
            <td><?php echo $opackage->DELIVERY_NO ?></td>
            <td><?php echo $opackage->REMARKS ?></td>
            <td><?php echo $opackage->MONEY ?></td>
            <td><?php echo $opackage->COURIER ?></td>
            <td><?php echo $opackage->SHOULD_PAY ?></td>
            <td><?php echo $opackage->CREATE_TIME ?></td>
            <td><?php echo $opackage->PACKAGE_ID ?></td>
            <td><?php echo $opackage->PAYMENT_STATUS ?></td>
            <td><?php echo $opackage->AGENCYID ?></td>
            <td><?php echo $opackage->AGENCY_ID ?></td>
            <td><?php echo $opackage->DELIVERY_COMPANY ?></td>
            <td><?php echo $opackage->ORDER_TOTAL_MONEY ?></td>
            <td><?php echo $opackage->ORDER_DISCOUNT_TOTAL_MONEY ?></td>
            <td><?php echo $opackage->VIRTUAL_MONEY ?></td>
            <td><?php echo $opackage->VIRTUAL_MONEY_TYPE ?></td>
            <td><?php echo $opackage->COD ?></td>
            <td><?php echo $opackage->PAYMENT_CLASS ?></td>
            <td><?php echo $opackage->REAL_PAY ?></td>
            <td><?php echo $opackage->USERNAME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("opackage/edit/".$opackage->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("opackage/delete/".$opackage->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="39" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("opackage/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("opackage/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("opackage/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("opackage/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>