<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("itemvideoinfo/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("itemvideoinfo/new", "Create item video info")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ITEM Of ID</th>
            <th>VIDEO Of URL</th>
            <th>IS Of VISIBLE</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $itemvideoinfo){ ?>
        <tr>
            <td><?php echo $itemvideoinfo->ID ?></td>
            <td><?php echo $itemvideoinfo->ITEM_ID ?></td>
            <td><?php echo $itemvideoinfo->VIDEO_URL ?></td>
            <td><?php echo $itemvideoinfo->IS_VISIBLE ?></td>
            <td><?php echo $itemvideoinfo->CREATE_TIME ?></td>
            <td><?php echo $itemvideoinfo->UPDATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemvideoinfo/edit/".$itemvideoinfo->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemvideoinfo/delete/".$itemvideoinfo->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="6" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("itemvideoinfo/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemvideoinfo/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemvideoinfo/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemvideoinfo/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>