<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("carrearageuser/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("carrearageuser/new", "Create c arrearage user")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>MOBILE Of PHONE</th>
            <th>CONTACT Of PHONE</th>
            <th>ADDRESS</th>
            <th>OFFICE</th>
            <th>DESCRIPTION</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
            <th>MAX Of OWED</th>
            <th>NOW Of OWED</th>
            <th>DAY Of OWED</th>
            <th>RELATE Of CITY Of IDS</th>
            <th>HIDDEN</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $carrearageuser){ ?>
        <tr>
            <td><?php echo $carrearageuser->ID ?></td>
            <td><?php echo $carrearageuser->NAME ?></td>
            <td><?php echo $carrearageuser->MOBILE_PHONE ?></td>
            <td><?php echo $carrearageuser->CONTACT_PHONE ?></td>
            <td><?php echo $carrearageuser->ADDRESS ?></td>
            <td><?php echo $carrearageuser->OFFICE ?></td>
            <td><?php echo $carrearageuser->DESCRIPTION ?></td>
            <td><?php echo $carrearageuser->CREATE_TIME ?></td>
            <td><?php echo $carrearageuser->UPDATE_TIME ?></td>
            <td><?php echo $carrearageuser->MAX_OWED ?></td>
            <td><?php echo $carrearageuser->NOW_OWED ?></td>
            <td><?php echo $carrearageuser->DAY_OWED ?></td>
            <td><?php echo $carrearageuser->RELATE_CITY_IDS ?></td>
            <td><?php echo $carrearageuser->HIDDEN ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("carrearageuser/edit/".$carrearageuser->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("carrearageuser/delete/".$carrearageuser->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="14" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuser/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuser/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuser/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("carrearageuser/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>