<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("itemtypelog/new", "Create Item type log")) ?>
</div>

<div align="center">
    <h1>Search item type log</h1>
    <?php echo \Phalcon\Tag::form(array("itemtypelog/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="T_ID">T Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("T_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USER_UUID">USER Of UUID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USER_UUID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USER_NAME">USER Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USER_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CONTENT">CONTENT</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("CONTENT", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>