<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("itemtypelog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("itemtypelog/new", "Create item type log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>T Of ID</th>
            <th>USER Of UUID</th>
            <th>USER Of NAME</th>
            <th>CONTENT</th>
            <th>CREATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $itemtypelog){ ?>
        <tr>
            <td><?php echo $itemtypelog->ID ?></td>
            <td><?php echo $itemtypelog->T_ID ?></td>
            <td><?php echo $itemtypelog->USER_UUID ?></td>
            <td><?php echo $itemtypelog->USER_NAME ?></td>
            <td><?php echo $itemtypelog->CONTENT ?></td>
            <td><?php echo $itemtypelog->CREATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemtypelog/edit/".$itemtypelog->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemtypelog/delete/".$itemtypelog->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="6" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtypelog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtypelog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtypelog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemtypelog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>