<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("aartistinfo/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("aartistinfo/new", "Create a artist info")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ARTIST Of NAME</th>
            <th>ARTIST Of EN Of NAME</th>
            <th>ARTIST Of SPELL</th>
            <th>ARTIST Of AREA</th>
            <th>ARTIST Of TYPE</th>
            <th>IS Of VISIBLE</th>
            <th>ARTIST Of OCCUPATION</th>
            <th>ARTIST Of DESC</th>
            <th>ARTIST Of IMAGE Of URL</th>
            <th>ARTIST Of BIRTHDAY</th>
            <th>CREATE Of TIME</th>
            <th>UPDATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $aartistinfo){ ?>
        <tr>
            <td><?php echo $aartistinfo->ID ?></td>
            <td><?php echo $aartistinfo->ARTIST_NAME ?></td>
            <td><?php echo $aartistinfo->ARTIST_EN_NAME ?></td>
            <td><?php echo $aartistinfo->ARTIST_SPELL ?></td>
            <td><?php echo $aartistinfo->ARTIST_AREA ?></td>
            <td><?php echo $aartistinfo->ARTIST_TYPE ?></td>
            <td><?php echo $aartistinfo->IS_VISIBLE ?></td>
            <td><?php echo $aartistinfo->ARTIST_OCCUPATION ?></td>
            <td><?php echo $aartistinfo->ARTIST_DESC ?></td>
            <td><?php echo $aartistinfo->ARTIST_IMAGE_URL ?></td>
            <td><?php echo $aartistinfo->ARTIST_BIRTHDAY ?></td>
            <td><?php echo $aartistinfo->CREATE_TIME ?></td>
            <td><?php echo $aartistinfo->UPDATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("aartistinfo/edit/".$aartistinfo->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("aartistinfo/delete/".$aartistinfo->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="13" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("aartistinfo/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("aartistinfo/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("aartistinfo/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("aartistinfo/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>