<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("oorderticketlog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("oorderticketlog/new", "Create o order ticket log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ORDER Of ID</th>
            <th>TICKET Of ID</th>
            <th>SCREENINGS</th>
            <th>UUID</th>
            <th>NAME</th>
            <th>OLD Of STATUS</th>
            <th>NEW Of STATUS</th>
            <th>DESCRIBE</th>
            <th>CREATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $oorderticketlog){ ?>
        <tr>
            <td><?php echo $oorderticketlog->ID ?></td>
            <td><?php echo $oorderticketlog->ORDER_ID ?></td>
            <td><?php echo $oorderticketlog->TICKET_ID ?></td>
            <td><?php echo $oorderticketlog->SCREENINGS ?></td>
            <td><?php echo $oorderticketlog->UUID ?></td>
            <td><?php echo $oorderticketlog->NAME ?></td>
            <td><?php echo $oorderticketlog->OLD_STATUS ?></td>
            <td><?php echo $oorderticketlog->NEW_STATUS ?></td>
            <td><?php echo $oorderticketlog->DESCRIBE ?></td>
            <td><?php echo $oorderticketlog->CREATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("oorderticketlog/edit/".$oorderticketlog->ID, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("oorderticketlog/delete/".$oorderticketlog->ID, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="10" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderticketlog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderticketlog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderticketlog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("oorderticketlog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>