<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("accesslog/new", "Create Accesslog")) ?>
</div>

<div align="center">
    <h1>Search Accesslog</h1>
    <?php echo \Phalcon\Tag::form(array("accesslog/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SOURCE">SOURCE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SOURCE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="IP">IP</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("IP", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>