<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("accesslog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("accesslog/new", "Create access log")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>SOURCE</th>
            <th>IP</th>
            <th>CREATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $accesslog){ ?>
        <tr>
            <td><?php echo $accesslog->ID ?></td>
            <td><?php echo $accesslog->SOURCE ?></td>
            <td><?php echo $accesslog->IP ?></td>
            <td><?php echo $accesslog->CREATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("accesslog/edit/"., "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("accesslog/delete/"., "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="4" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("accesslog/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("accesslog/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("accesslog/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("accesslog/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>