<?php echo \Phalcon\Tag::form("onlinechoose/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("onlinechoose", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create online choose</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="ITEM_ID">ITEM Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ITEM_ID", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SENCE_ID">SENCE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SENCE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="FILE_ID">FILE Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("FILE_ID", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
