<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("itemlink/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("itemlink/new", "Create item link")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID</th>
            <th>ITEM Of ID</th>
            <th>ONLINE Of ID</th>
            <th>LINK</th>
            <th>CREATE Of TIME</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $itemlink){ ?>
        <tr>
            <td><?php echo $itemlink->ID ?></td>
            <td><?php echo $itemlink->ITEM_ID ?></td>
            <td><?php echo $itemlink->ONLINE_ID ?></td>
            <td><?php echo $itemlink->LINK ?></td>
            <td><?php echo $itemlink->CREATE_TIME ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemlink/edit/"., "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("itemlink/delete/"., "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="5" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("itemlink/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemlink/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemlink/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("itemlink/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>