<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("bbbenroll/new", "Create Bbb enroll")) ?>
</div>

<div align="center">
    <h1>Search bbb enroll</h1>
    <?php echo \Phalcon\Tag::form(array("bbbenroll/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="NAME">NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PHONE">PHONE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PHONE", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SCORE">SCORE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SCORE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="UPDATETIME">UPDATETIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("UPDATETIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CRTIME">CRTIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CRTIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="VERSION">VERSION</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("VERSION", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="SHARELINK">SHARELINK</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("SHARELINK", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>