<?php echo \Phalcon\Tag::form("ppaymenttype/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("ppaymenttype", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create p payment type</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="ID">ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="PARTNER_TYPE">PARTNER Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("PARTNER_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TYPE_NAME">TYPE Of NAME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("TYPE_NAME", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="TYPE_PARAMS">TYPE Of PARAMS</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textArea(array("TYPE_PARAMS", "cols" => "40", "rows" => "5")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="USE_STATUS">USE Of STATUS</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("USE_STATUS", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="CREATE_TIME">CREATE Of TIME</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("CREATE_TIME", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="AGENCY_ID">AGENCY Of ID</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("AGENCY_ID", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="COMISSION_RATE">COMISSION Of RATE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("COMISSION_RATE", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="DEFAULT_PARTNER_TYPE">DEFAULT Of PARTNER Of TYPE</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("DEFAULT_PARTNER_TYPE", "type" => "numeric")) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
